# Generated by Django 5.0.7 on 2024-08-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
