# Generated by Django 5.0.7 on 2024-08-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_sms_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='body',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='title',
        ),
    ]
